version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017

  db:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - ./postgres.env
